### ISSUE TITLE
Prepare Aref Ruqaa Ink for Google Fonts

### ISSUE THREAD

**Issue by yanone** [aliftype/aref-ruqaa#37]
Hi Khaled,

I'm commissioned to onboard Aref Ruqaa Ink to Google Fonts.

Before I can even check the provided files, I need to ask you to please provide TTF files in the repository. Sadly I couldn't get anything to build:

```
(aref) yanone@Yanones-MBP aref-ruqaa % make ttf            
   BUILD  ArefRuqaa-Regular.ttf
/Users/yanone/Projekte/Google/Onboarding/aref-ruqaa/aref/bin/python3: No module named fontmake
```

Thank you.

**Comment by khaledhosny** [comment]
The TTFs are provided in the releases. As for build, you obviously need to install the requirements first.

**Comment by yanone** [comment]
> The TTFs are provided in the releases. 

Ah yes, thanks

> As for build, you obviously need to install the requirements first.

I did ;) in a venv. It didn't work.

**Comment by khaledhosny** [comment]
> > As for build, you obviously need to install the requirements first.
> 
> I did ;) in a venv. It didn't work.

It works locally and on the ci, so I have no idea why it isn’t working for you.

**Comment by qirh** [comment]
> > The TTFs are provided in the releases.
> 
> Ah yes, thanks
> 
> > As for build, you obviously need to install the requirements first.
> 
> I did ;) in a venv. It didn't work.

From the error it seems like your `env` doesn't have the package. Are you sure you are using the right python executable? check by typing `which python`. If that is correct. Can you list the packages in your `env`? You can do so by `pip list`

**Comment by yanone** [comment]
Hi Khaled,

posting the Fontbakery report for the v.1004 TTF files. It requires roughly the same changes as I've previously posted for Amiri: one name table issue, apply decompose transformed components filter, and prep table issue regarding non-hinted fonts.
If you could please have a look.
Thank you


## Fontbakery report

Fontbakery version: 0.8.9.dev13+gd73f3da0

<details><summary><b>[3] ArefRuqaaInk-Bold.ttf</b></summary><div><details><summary>🔥 <b>FAIL:</b> Font enables smart dropout control in "prep" table instructions? (<a href="https://font-bakery.readthedocs.io/en/stable/fontbakery/profiles/googlefonts.html#com.google.fonts/check/smart_dropout">com.google.fonts/check/smart_dropout</a>)</summary><div>

>
>This setup is meant to ensure consistent rendering quality for fonts across all devices (with different rendering/hinting capabilities).
>
>Below is the snippet of instructions we expect to see in the fonts:
>B8 01 FF    PUSHW 0x01FF
>85          SCANCTRL (unconditinally turn on
>                      dropout control mode)
>B0 04       PUSHB 0x04
>8D          SCANTYPE (enable smart dropout control)
>
>"Smart dropout control" means activating rules 1, 2 and 5:
>Rule 1: If a pixel's center falls within the glyph outline,
>        that pixel is turned on.
>Rule 2: If a contour falls exactly on a pixel's center,
>        that pixel is turned on.
>Rule 5: If a scan line between two adjacent pixel centers
>        (either vertical or horizontal) is intersected
>        by both an on-Transition contour and an off-Transition
>        contour and neither of the pixels was already turned on
>        by rules 1 and 2, turn on the pixel which is closer to
>        the midpoint between the on-Transition contour and
>        off-Transition contour. This is "Smart" dropout control.
>
>For more detailed info (such as other rules not enabled in this snippet), please refer to the TrueType Instruction Set documentation.
>
>
* 🔥 **FAIL** The 'prep' table does not contain TrueType instructions enabling smart dropout control. To fix, export the font with autohinting enabled, or run ttfautohint on the font, or run the `gftools fix-nonhinting` script. [code: lacks-smart-dropout]
</div></details><details><summary>🔥 <b>FAIL:</b> Name table strings must not contain the string 'Reserved Font Name'. (<a href="https://font-bakery.readthedocs.io/en/stable/fontbakery/profiles/googlefonts.html#com.google.fonts/check/name/rfn">com.google.fonts/check/name/rfn</a>)</summary><div>

>
>Some designers adopt the "Reserved Font Name" clause of the OFL license. This means that the original author reserves the rights to the family name and other people can only distribute modified versions using a different family name.
>
>Google Fonts published updates to the fonts in the collection in order to fix issues and/or implement further improvements to the fonts. It is important to keep the family name so that users of the webfonts can benefit from the updates. Since it would forbid such usage scenario, all families in the GFonts collection are required to not adopt the RFN clause.
>
>This check ensures "Reserved Font Name" is not mentioned in the name table.
>
>
* 🔥 **FAIL** Name table entry ("Copyright 2015-2022 The Aref Ruqaa Project Authors (https://github.com/aliftype/aref-ruqaa), with Reserved Font Name EURM10.") contains "Reserved Font Name". This is an error except in a few specific rare cases. [code: rfn]
</div></details><details><summary>🔥 <b>FAIL:</b> Ensure component transforms do not perform scaling or rotation. (<a href="https://font-bakery.readthedocs.io/en/stable/fontbakery/profiles/universal.html#com.google.fonts/check/transformed_components">com.google.fonts/check/transformed_components</a>)</summary><div>

>
>Some families have glyphs which have been constructed by using transformed components e.g the 'u' being constructed from a flipped 'n'.
>
>From a designers point of view, this sounds like a win (less work). However, such approaches can lead to rasterization issues, such as having the 'u' not sitting on the baseline at certain sizes after running the font through ttfautohint.
>
>As of July 2019, Marc Foley observed that ttfautohint assigns cvt values to transformed glyphs as if they are not transformed and the result is they render very badly, and that vttLib does not support flipped components.
>
>When building the font with fontmake, the problem can be fixed by adding this to the command line:
>--filter DecomposeTransformedComponentsFilter
>
>
* 🔥 **FAIL** The following glyphs had components with scaling or rotation:

* glyph00233 (component uni0621)
* glyph00420 (component uni0660)
* glyph00421 (component uni0661)
* glyph00422 (component uni0662)
* glyph00423 (component uni0663)
* glyph00424 (component uni0664)
* glyph00425 (component uni0665)
* glyph00426 (component uni0666)
* glyph00427 (component uni0667)
* glyph00428 (component uni0668)
* glyph00429 (component uni0669)
* glyph00430 (component uni06F2)
* glyph00431 (component uni06F4)
* glyph00432 (component uni06F5)
* glyph00433 (component uni06F6)
* glyph00434 (component uni0660)
* glyph00435 (component uni0661)
* glyph00436 (component uni0662)
* glyph00437 (component uni0663)
* glyph00438 (component uni0664)
* glyph00439 (component uni0665)
* glyph00440 (component uni0666)
* glyph00441 (component uni0667)
* glyph00442 (component uni0668)
* glyph00443 (component uni0669)
* glyph00444 (component uni06F2)
* glyph00445 (component uni06F4)
* glyph00446 (component uni06F5)
* glyph00447 (component uni06F6)
* glyph00450 (component glyph00448)
* glyph00451 (component glyph00449)
* glyph00452 (component glyph00448)
* glyph00453 (component glyph00449)
* glyph00457 (component uni060C)
* glyph00459 (component uni061B)
* uniFD3F (component uniFD3E)
* guillemotright (component guilsinglleft)
* guillemotright (component guilsinglleft)
* guilsinglright (component guilsinglleft)
* uni0657 (component uni064F)
 [code: transformed-components]
</div></details><br></div></details><details><summary><b>[3] ArefRuqaaInk-Regular.ttf</b></summary><div><details><summary>🔥 <b>FAIL:</b> Font enables smart dropout control in "prep" table instructions? (<a href="https://font-bakery.readthedocs.io/en/stable/fontbakery/profiles/googlefonts.html#com.google.fonts/check/smart_dropout">com.google.fonts/check/smart_dropout</a>)</summary><div>

>
>This setup is meant to ensure consistent rendering quality for fonts across all devices (with different rendering/hinting capabilities).
>
>Below is the snippet of instructions we expect to see in the fonts:
>B8 01 FF    PUSHW 0x01FF
>85          SCANCTRL (unconditinally turn on
>                      dropout control mode)
>B0 04       PUSHB 0x04
>8D          SCANTYPE (enable smart dropout control)
>
>"Smart dropout control" means activating rules 1, 2 and 5:
>Rule 1: If a pixel's center falls within the glyph outline,
>        that pixel is turned on.
>Rule 2: If a contour falls exactly on a pixel's center,
>        that pixel is turned on.
>Rule 5: If a scan line between two adjacent pixel centers
>        (either vertical or horizontal) is intersected
>        by both an on-Transition contour and an off-Transition
>        contour and neither of the pixels was already turned on
>        by rules 1 and 2, turn on the pixel which is closer to
>        the midpoint between the on-Transition contour and
>        off-Transition contour. This is "Smart" dropout control.
>
>For more detailed info (such as other rules not enabled in this snippet), please refer to the TrueType Instruction Set documentation.
>
>
* 🔥 **FAIL** The 'prep' table does not contain TrueType instructions enabling smart dropout control. To fix, export the font with autohinting enabled, or run ttfautohint on the font, or run the `gftools fix-nonhinting` script. [code: lacks-smart-dropout]
</div></details><details><summary>🔥 <b>FAIL:</b> Name table strings must not contain the string 'Reserved Font Name'. (<a href="https://font-bakery.readthedocs.io/en/stable/fontbakery/profiles/googlefonts.html#com.google.fonts/check/name/rfn">com.google.fonts/check/name/rfn</a>)</summary><div>

>
>Some designers adopt the "Reserved Font Name" clause of the OFL license. This means that the original author reserves the rights to the family name and other people can only distribute modified versions using a different family name.
>
>Google Fonts published updates to the fonts in the collection in order to fix issues and/or implement further improvements to the fonts. It is important to keep the family name so that users of the webfonts can benefit from the updates. Since it would forbid such usage scenario, all families in the GFonts collection are required to not adopt the RFN clause.
>
>This check ensures "Reserved Font Name" is not mentioned in the name table.
>
>
* 🔥 **FAIL** Name table entry ("Copyright 2015-2022 The Aref Ruqaa Project Authors (https://github.com/aliftype/aref-ruqaa), with Reserved Font Name EURM10.") contains "Reserved Font Name". This is an error except in a few specific rare cases. [code: rfn]
</div></details><details><summary>🔥 <b>FAIL:</b> Ensure component transforms do not perform scaling or rotation. (<a href="https://font-bakery.readthedocs.io/en/stable/fontbakery/profiles/universal.html#com.google.fonts/check/transformed_components">com.google.fonts/check/transformed_components</a>)</summary><div>

>
>Some families have glyphs which have been constructed by using transformed components e.g the 'u' being constructed from a flipped 'n'.
>
>From a designers point of view, this sounds like a win (less work). However, such approaches can lead to rasterization issues, such as having the 'u' not sitting on the baseline at certain sizes after running the font through ttfautohint.
>
>As of July 2019, Marc Foley observed that ttfautohint assigns cvt values to transformed glyphs as if they are not transformed and the result is they render very badly, and that vttLib does not support flipped components.
>
>When building the font with fontmake, the problem can be fixed by adding this to the command line:
>--filter DecomposeTransformedComponentsFilter
>
>
* 🔥 **FAIL** The following glyphs had components with scaling or rotation:

* glyph00233 (component uni0621)
* glyph00420 (component uni0660)
* glyph00421 (component uni0661)
* glyph00422 (component uni0662)
* glyph00423 (component uni0663)
* glyph00424 (component uni0664)
* glyph00425 (component uni0665)
* glyph00426 (component uni0666)
* glyph00427 (component uni0667)
* glyph00428 (component uni0668)
* glyph00429 (component uni0669)
* glyph00430 (component uni06F2)
* glyph00431 (component uni06F4)
* glyph00432 (component uni06F5)
* glyph00433 (component uni06F6)
* glyph00434 (component uni0660)
* glyph00435 (component uni0661)
* glyph00436 (component uni0662)
* glyph00437 (component uni0663)
* glyph00438 (component uni0664)
* glyph00439 (component uni0665)
* glyph00440 (component uni0666)
* glyph00441 (component uni0667)
* glyph00442 (component uni0668)
* glyph00443 (component uni0669)
* glyph00444 (component uni06F2)
* glyph00445 (component uni06F4)
* glyph00446 (component uni06F5)
* glyph00447 (component uni06F6)
* glyph00450 (component glyph00448)
* glyph00451 (component glyph00449)
* glyph00452 (component glyph00448)
* glyph00453 (component glyph00449)
* glyph00457 (component uni060C)
* glyph00459 (component uni061B)
* uniFD3F (component uniFD3E)
* guillemotright (component guilsinglleft)
* guillemotright (component guilsinglleft)
* guilsinglright (component guilsinglleft)
* uni0657 (component uni064F)
 [code: transformed-components]
</div></details><br></div></details>
### Summary

| 💔 ERROR | 🔥 FAIL | ⚠ WARN | 💤 SKIP | ℹ INFO | 🍞 PASS | 🔎 DEBUG |
|:-----:|:----:|:----:|:----:|:----:|:----:|:----:|
| 0 | 6 | 22 | 229 | 13 | 164 | 0 |
| 0% | 1% | 5% | 53% | 3% | 38% | 0% |

**Note:** The following loglevels were omitted in this report:
* **WARN**
* **SKIP**
* **INFO**
* **PASS**
* **DEBUG**

**Comment by khaledhosny** [comment]
> `com.google.fonts/check/smart_dropout`

Version 1.005 should have `prep` table.

> `com.google.fonts/check/name/rfn`

The ”Reserved Font Name” is not mine to remove, I inherited it from the Latin part.

> `com.google.fonts/check/transformed_components`

This again is a file size saving trick that I intend to keep, the rational does not convince me since I’m not using any autohinting.

**Comment by khaledhosny** [comment]
https://github.com/googlefonts/fontbakery/issues/3738

**Comment by khaledhosny** [comment]
https://github.com/googlefonts/fontbakery/issues/3739
