### ISSUE TITLE
Adding a letter ڭ

### ISSUE THREAD

**Issue by IlyasTarpan** [aliftype/aref-ruqaa#40]
Hello! I want to thank you for creating such a beautiful and proportional Aref Ruqaa font!
  I am a native speaker of the Crimean Tatar language and the Crimean Tatars actively used the handwriting "hand". There is one letter in the Crimean Tatar alphabet that is not in your font - the letter ڭ. (By the way, this letter is also in the Ottoman alphabet). This is a mandatory letter, and I miss it so much when I write in Crimean Tatar in your font!
  I ask you to add this letter to your font.
The letter should look like this:

مرحبًا! أود أن أشكركم على إنشاء خط عارف الرقعة الجميل والمتناسب!
  أنا متحدث أصلي للغة تتار القرم وكان تتار القرم يستخدمون بنشاط خط اليد "رقعة". هناك حرف واحد في الأبجدية التتار القرم ليس في الخط الخاص بك - الحرف ڭ. (بالمناسبة ، هذا الحرف موجود أيضًا في الأبجدية العثمانية). هذه رسالة إلزامية ، وأفتقدها كثيرًا عندما أكتب بلغة تتار القرم بالخط الخاص بك!
  أطلب منك إضافة هذه الرسالة إلى الخط الخاص بك.
يجب أن تبدو الرسالة كما يلي:
![Снимок экрана (1484)](https://user-images.githubusercontent.com/113206717/189544788-6110aa96-d9c4-4cd9-b47a-2501b1da372e.png)
![Снимок экрана (1468)](https://user-images.githubusercontent.com/113206717/189544807-ae922516-3d63-47e7-a97e
![Снимок экрана (1483)](https://user-images.githubusercontent.com/113206717/189544896-d78cf095-20d0-4491-9618-4bfedf7c5596.png)
-c76872827ab3.png)
![Снимок экрана (1482)](https://user-images.githubusercontent.com/113206717/189544810-380c9b72-13b0-4093-b2b5-181ae797c6b8.png)
![Снимок экрана (1481)](https://user-images.githubusercontent.com/113206717/189544936-6d5688a2-39dd-467b-8fc4-2f38a94fd791.png)
![Снимок экрана (1473)](https://user-images.githubusercontent.com/113206717/189544949-ee73b218-a3be-4e90-8101-6b4c4766b346.png)
![Снимок экрана (1480)](https://user-images.githubusercontent.com/113206717/189544950-73252f10-5054-4ddc-b1bf-7326dc41666c.png)
![Снимок экрана (1479)](https://user-images.githubusercontent.com/113206717/189544951-f360200b-c364-45a8-a85d-63e3940fed81.png)
![Снимок экрана (1478)](https://user-images.githubusercontent.com/113206717/189544954-70a8975e-b7d0-44d9-ae23-f534c47ee62d.png)
![Снимок экрана (1477)](https://user-images.githubusercontent.com/113206717/189544955-ebca7aef-d6de-4802-9254-94cef4d47523.png)
![Снимок экрана (1476)](https://user-images.githubusercontent.com/113206717/189544956-37116886-8a56-4602-b1d7-d9568e4ca594.png)
![Снимок экрана (1475)](https://user-images.githubusercontent.com/113206717/189544957-cb6c9294-dd63-4583-9e59-206efcc441dc.png)
![Снимок экрана (1474)](https://user-images.githubusercontent.com/113206717/189544960-12112514-1408-43f1-9216-2352ce491202.png)

**Comment by khaledhosny** [comment]
<img width="879" alt="image" src="https://user-images.githubusercontent.com/93914/192197951-6efe372f-e1d6-4e6c-97bb-6971bcdc5b03.png">

**Comment by IlyasTarpan** [comment]
شكرا جزيلا لك! أنا جديد ، فهل يمكنك إخباري أين يمكنني تنزيل أحدث إصدار من الخط؟
أيضًا ، يمكنني أن أطلب منك إضافة أحدث إصدار إلى خطوط جوجل حتى يتمكن مواطنو بلدي من تنزيله؟

Thank you very much! I'm new, so can you tell me where can I download the newest version of the font?
Also, I can ask you to add the latest version to Google fonts so that my compatriots can download it?
![Снимок экрана (1492)](https://user-images.githubusercontent.com/113206717/192304859-d447855d-ec6b-483d-a09f-def7bd469fdc.png)

**Comment by khaledhosny** [comment]
You can download the latest version from https://github.com/aliftype/aref-ruqaa/releases, for Google Fonts you will have to report the outdated version at https://github.com/google/fonts/issues
